name: yugiohgalaxy
version: 1.1.3+96
publish_to: none
description: yugiohgalaxy app
environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  after_layout: any
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8

  dartz: ^0.10.1
  dotted_border: ^2.0.0+3

  flutter:
    sdk: flutter
  flutter_debouncer: ^2.0.0
  flutter_dotenv: ^5.0.2

  flutter_localizations:
    sdk: flutter
  flutter_network_connectivity: any

  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^4.8.0
  fluttertoast: ^8.2.5
  form_builder_extra_fields:
    git: https://github.com/JeanM1996/form_builder_extra_fields.git
  freezed_annotation: ^2.2.0
  go_router: ^14.1.1

  hive_flutter: any
  http: ^1.2.1

  intl: ^0.19.0
  injectable: any
  logger: ^2.3.0

  path_provider: ^2.1.3
  share_plus: ^9.0.0
  simple_gesture_detector: ^0.2.0
  url_launcher: ^6.2.6
  whatsapp_share: ^2.0.2
  widget_screenshot: any

dependency_overrides:
  flutter_colorpicker:
    git:
      url: https://github.com/mchome/flutter_colorpicker
      ref: master

dev_dependencies:
  build_runner: ^2.4.10
  dart_code_linter: ^1.1.1
  flutter_test:
    sdk: flutter
  freezed: any
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mockito: any
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - env
    - env.alpha
    - env.beta
    - env.staging
    - assets/images/
    - assets/icons/
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree/Figtree-Black.ttf
          weight: 900
        - asset: assets/fonts/Figtree/Figtree-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Figtree/Figtree-Bold.ttf
          weight: 700
        - asset: assets/fonts/Figtree/Figtree-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Figtree/Figtree-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Figtree/Figtree-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Figtree/Figtree-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Figtree/Figtree-Light.ttf
          weight: 300
        - asset: assets/fonts/Figtree/Figtree-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Figtree/Figtree-Medium.ttf
          weight: 500
        - asset: assets/fonts/Figtree/Figtree-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Figtree/Figtree-Regular.ttf
          weight: 400
        - asset: assets/fonts/Figtree/Figtree-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Figtree/Figtree-SemiBoldItalic.ttf
          style: italic
          weight: 600
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
  uses-material-design: true
