// Mocks generated by Mockito 5.4.4 from annotations
// in yugiohgalaxy/test/features/arquetipes_section/data/repositories/arquetipes_section_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yugiohgalaxy/core/data/network/http_client.dart' as _i2;
import 'package:yugiohgalaxy/features/arquetipes_section/data/data_sources/arquetipes_section_data_source.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpServiceResponse_0 extends _i1.SmartFake
    implements _i2.HttpServiceResponse {
  _FakeHttpServiceResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArquetipeSectionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArquetipeSectionDataSource extends _i1.Mock
    implements _i3.ArquetipeSectionDataSource {
  MockArquetipeSectionDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpServiceResponse> getCardDetail(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCardDetail,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpServiceResponse>.value(
            _FakeHttpServiceResponse_0(
          this,
          Invocation.method(
            #getCardDetail,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpServiceResponse>);

  @override
  _i4.Future<_i2.HttpServiceResponse> getArquetipes() => (super.noSuchMethod(
        Invocation.method(
          #getArquetipes,
          [],
        ),
        returnValue: _i4.Future<_i2.HttpServiceResponse>.value(
            _FakeHttpServiceResponse_0(
          this,
          Invocation.method(
            #getArquetipes,
            [],
          ),
        )),
      ) as _i4.Future<_i2.HttpServiceResponse>);

  @override
  _i4.Future<_i2.HttpServiceResponse> getCardArquetipes(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCardArquetipes,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpServiceResponse>.value(
            _FakeHttpServiceResponse_0(
          this,
          Invocation.method(
            #getCardArquetipes,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpServiceResponse>);

  @override
  _i4.Future<_i2.HttpServiceResponse> getCardsFromBanlist(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCardsFromBanlist,
          [id],
        ),
        returnValue: _i4.Future<_i2.HttpServiceResponse>.value(
            _FakeHttpServiceResponse_0(
          this,
          Invocation.method(
            #getCardsFromBanlist,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.HttpServiceResponse>);
}
